config/routes.rb
Blog::Application.routes.draw do
  root to: "posts#index"

  resources :posts do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_post

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(params[:comment])
    if @comment.save
      flash[:success] = "Comment was created successfully"
      redirect_to [@post, @comment]
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end



  private

    def find_post
      @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController  < ApplicationController
  before_filter :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
      flash[:success] = "Post was created successfully"
      redirect_to @post
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:success] = "Post was updated successfully"
      redirect_to @post
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post was deleted successfully"
      redirect_to posts_path
    else
      flash[:error] = "Something went wrong"
      redirect_to edit_post_path(@post)
    end    
  end

  private

    def find_post
      @post = Post.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment], html: { class: "form-horizontal" } do |f| %>
  <%= render 'layouts/error_messages', f: f.object %>

  <div class="control-group">
    <%= f.label :body, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :body %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
    
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p><%= @comment.body %></p>

app/views/layouts/_error_messages.html.erb
<% if f.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(f.errors.count, "error") %>.
    </div>
    <ul>
    <% f.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="span12">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>  

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { class: "form-horizontal" } do |f| %>
  <%= render 'layouts/error_messages', f: f.object %>

  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :body, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :body %>
    </div>
  </div>


  <div class="control-group">
    <div class="controls">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
    
<% end %>

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

<%= render 'form' %>

<%= link_to "Delete Post", post_path(@post), method: "delete", data: { confirm: 'Are you sure?' } %>

app/views/posts/index.html.erb
<h1>All Post</h1>

<ul>
<% @posts.each do |p| %>
  <li><%= p.title %></li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>

  <%= f.label :title %><br />
  <%= f.text_field :title %>

  <%= f.label :body %><br />
  <%= f.text_area :body %>

  <%= f.submit %>
  
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<hr />

<h2>Comments</h2>

<% @post.comments.each do |c| %>
  <li><%= c.body %>, <%= c.created_at.strftime("%B #{c.created_at.day.ordinalize} %Y %H:%M") %></li>
<% end %>